# Generated by Django 5.2.14 on 2026-05-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionTransicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('python_path', 'Python Path'), ('json_logic', 'JSON Logic'), ('django_orm', 'Django ORM Lookup')], max_length=20, verbose_name='Tipo de condición')),
                ('configuracion', models.JSONField(help_text='Parámetros específicos del backend.', verbose_name='Configuración')),
                ('mensaje_error', models.CharField(default='No cumple con las condiciones requeridas.', max_length=250, verbose_name='Mensaje de error')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de evaluación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('transicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='sinpapel.configuraciontransicion', verbose_name='Transición')),
            ],
            options={
                'verbose_name': 'Condición de Transición',
                'verbose_name_plural': 'Condiciones de Transición',
                'db_table': 'sinpapel_condiciontransicion',
                'ordering': ['orden'],
            },
        ),
    ]
