# Generated by Django 5.2.8 on 2026-04-27 04:56

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sinpapel', '0002_extract_remaining_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalConfiguracionTransicion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('estado_destino', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.estado', verbose_name='Estado destino')),
                ('estado_origen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.estado', verbose_name='Estado origen')),
                ('flujo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.versionflujo', verbose_name='Versión de Flujo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transición',
                'verbose_name_plural': 'historical Transiciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalConfiguracionTransicion_grupos_permitidos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('configuraciontransicion', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.configuraciontransicion')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='sinpapel.historicalconfiguraciontransicion')),
            ],
            options={
                'verbose_name': 'HistoricalConfiguracionTransicion_grupos_permitidos',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstanciaDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actualizado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de entidad')),
                ('archivo_generado', models.TextField(blank=True, max_length=100, null=True)),
                ('actor_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de actor')),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('actor_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de actor')),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.documento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de entidad')),
            ],
            options={
                'verbose_name': 'historical Instancia de Documento',
                'verbose_name_plural': 'historical Instancias de Documentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRegistroFirma',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('backend_name', models.CharField(default='fiel', help_text='Identificador del backend de firma (fiel, pades, docusign, manual, etc.)', max_length=50, verbose_name='Backend')),
                ('backend_metadata', models.JSONField(blank=True, default=dict, help_text='Datos específicos del backend (FIEL: pkcs7, cert, rfc, serie; etc.)', verbose_name='Metadata del Backend')),
                ('signer_display_name', models.CharField(help_text='Nombre del firmante para visualización (puede no coincidir con User.get_full_name).', max_length=255, verbose_name='Nombre del Firmante')),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de entidad firmada')),
                ('content_hash', models.CharField(help_text='SHA-256 hex del payload canónico firmado', max_length=128, verbose_name='Hash del contenido firmado')),
                ('is_required', models.BooleanField(default=False, help_text='True si la transición exigía firma obligatoria', verbose_name='¿Firma requerida?')),
                ('verification_result', models.CharField(choices=[('VALIDA', 'Válida'), ('INVALIDA', 'Inválida'), ('PENDIENTE', 'Pendiente de verificación')], default='PENDIENTE', max_length=10, verbose_name='Resultado de validación')),
                ('signed_at', models.DateTimeField(help_text='Momento en que se realizó la firma (según el cliente)', verbose_name='Timestamp de firma')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('signer', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuario interno que firmó. NULL si la firma es externa.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Firmante (User)')),
                ('target_content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Tipo de entidad firmada')),
            ],
            options={
                'verbose_name': 'historical Registro de Firma',
                'verbose_name_plural': 'historical Registros de Firma',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRequisitoEstadoDocumento',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('actualizado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('porcentaje', models.IntegerField(default=100, help_text='Porcentaje mínimo requerido (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_carga', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('autor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.estado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_documento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sinpapel.tipodocumento')),
            ],
            options={
                'verbose_name': 'historical Requisito Estado-Documento',
                'verbose_name_plural': 'historical Requisitos Estado-Documento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVersionFlujo',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=False, help_text='Desactivar retira el flujo de todos los productos asignados (fallback al dict).', verbose_name='Activo')),
                ('metadatos', models.JSONField(blank=True, help_text='Posiciones de nodos en el canvas: {positions: {estado_id: {x, y}}}', null=True, verbose_name='Metadatos')),
                ('creado', models.DateTimeField(blank=True, editable=False, verbose_name='Creado en')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Versión de Flujo',
                'verbose_name_plural': 'historical Versiones de Flujo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
