# Generated by Django 5.2.14 on 2026-05-15 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0002_condiciontransicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_maximos', models.PositiveIntegerField(help_text='Tiempo máximo permitido en este estado antes de ejecutar la acción.', verbose_name='Días máximos')),
                ('accion_vencimiento', models.CharField(choices=[('notificar', 'Notificar'), ('escalar', 'Escalar'), ('rechazar', 'Rechazar'), ('alertar', 'Alertar / Bandera')], max_length=20, verbose_name='Acción al vencer')),
                ('configuracion_accion', models.JSONField(blank=True, default=dict, help_text='Parámetros específicos de la acción (ver documentación).', verbose_name='Configuración de acción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='sinpapel.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
                'db_table': 'sinpapel_sla_configuracion',
                'unique_together': {('estado', 'accion_vencimiento')},
            },
        ),
    ]
