# Generated by Django 6.0.5 on 2026-06-25 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0003_slaconfiguracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanciadocumento',
            name='porcentaje',
            field=models.IntegerField(default=100, help_text='Porcentaje de completitud del documento (0-100). Se compara contra RequisitoEstadoDocumento.porcentaje al evaluar una transición. Default 100 (documento completo) para backward-compatibility.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de completitud'),
        ),
        migrations.AddField(
            model_name='instanciadocumento',
            name='porcentaje',
            field=models.IntegerField(default=100, help_text='Porcentaje de completitud del documento (0-100). Se compara contra RequisitoEstadoDocumento.porcentaje al evaluar una transición. Default 100 (documento completo) para backward-compatibility.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de completitud'),
        ),
    ]
