# Generated by Django 6.0.5 on 2026-06-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0004_historicalinstanciadocumento_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstanciadocumento',
            name='archivo',
            field=models.TextField(blank=True, help_text='Archivo subido por el usuario para satisfacer un requisito documental (distinto de archivo_generado, que produce el sistema).', max_length=100, null=True, verbose_name='Archivo subido'),
        ),
        migrations.AddField(
            model_name='instanciadocumento',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo subido por el usuario para satisfacer un requisito documental (distinto de archivo_generado, que produce el sistema).', null=True, upload_to='instancias_documento/', verbose_name='Archivo subido'),
        ),
    ]
