# Generated by Django 6.0.5 on 2026-06-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0005_historicalinstanciadocumento_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientoworkflow',
            name='monto_aprobado',
        ),
    ]
