# Generated by Django 6.0.5 on 2026-08-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0006_remove_seguimientoworkflow_monto_aprobado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sinpapel.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estado',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expedienteadjunto',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expedienteadjunto',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instanciadocumento',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instanciadocumento',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sinpapel.documento'),
        ),
        migrations.AlterField(
            model_name='instanciadocumento',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='razonrechazodocumento',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='razonrechazodocumento',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitoestadodocumento',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitoestadodocumento',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimientoworkflow',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='seguimientoworkflow',
            name='firma_registro',
            field=models.OneToOneField(blank=True, help_text='Evidencia criptográfica de la firma electrónica (si se firmó)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguimiento', to='sinpapel.registrofirma', verbose_name='Registro de Firma'),
        ),
        migrations.AlterField(
            model_name='seguimientoworkflow',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='estado',
            constraint=models.UniqueConstraint(fields=('nombre',), name='sin_estado_nombre_uniq'),
        ),
        migrations.AddConstraint(
            model_name='versionflujo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('nombre',), name='sin_versionflujo_activa_uniq'),
        ),
    ]
