# Generated by Django 6.0.5 on 2026-08-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinpapel', '0007_alter_documento_autor_alter_documento_modificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontransicion',
            name='requiere_firma',
            field=models.BooleanField(default=False, help_text='Si es True, la transición exige firma_payload: el motor rechaza ejecutarla sin firma electrónica del usuario.', verbose_name='Requiere firma electrónica'),
        ),
        migrations.AddField(
            model_name='historicalconfiguraciontransicion',
            name='requiere_firma',
            field=models.BooleanField(default=False, help_text='Si es True, la transición exige firma_payload: el motor rechaza ejecutarla sin firma electrónica del usuario.', verbose_name='Requiere firma electrónica'),
        ),
    ]
