# Generated by Django 6.0.5 on 2026-05-18 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sinpapel', '0003_slaconfiguracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('flujo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sinpapel.versionflujo')),
            ],
        ),
        migrations.CreateModel(
            name='TestProductoVersionFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sinpapel.versionflujo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.testproducto')),
            ],
        ),
        migrations.CreateModel(
            name='TestSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sinpapel.estado')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.testproducto')),
            ],
        ),
        migrations.CreateModel(
            name='TestSolicitudConMetadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sinpapel.estado')),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
