# Generated by Django 6.0.5 on 2026-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
            ],
        ),
    ]
