# Generated by Django 6.0.5 on 2026-05-18 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_testformmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCapturable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
            ],
        ),
        migrations.CreateModel(
            name='TestEmptySchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_capturados', models.JSONField(blank=True, default=dict, verbose_name='Datos capturados')),
            ],
        ),
        migrations.CreateModel(
            name='TestCatalogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('color', models.CharField(default='#4DEFE2', max_length=7)),
                ('orden', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, max_length=1000, null=True, upload_to='portadas/', verbose_name='Miniatura')),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('extra', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestTrazableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True, null=True)),
                ('caducidad', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL)),
                ('modificador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
