# Generated by Django 6.0.5 on 2026-08-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_testcapturable_testemptyschema_testcatalogomodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcatalogomodel',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testcatalogomodel',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsolicitud',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsolicitud',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsolicitudconmetadatos',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testsolicitudconmetadatos',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testtrazablemodel',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testtrazablemodel',
            name='modificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificador', to=settings.AUTH_USER_MODEL),
        ),
    ]
