# Generated by Django 6.0.5 on 2026-08-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testcatalogomodel_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsolicitud',
            name='alerta_sla',
            field=models.BooleanField(default=False),
        ),
    ]
